<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<p class="flex items-center text-red">
    <span class="inline-block w-8 h-8"><?= $heroicons->exclamationCircleHtml('',32,32); ?></span>
    <span><?= $escaper->escapeHtml(__("Could not load SendCloud service points")); ?></span>
</p>
